version: '2'
services:
    telestat-mariadb:
        image: mariadb:10.1.17
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=verify
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
        restart: always
            # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
# docker-compose -f mariadb.yml up -d
# docker-compose -f mariadb.yml down