version: '2'
services:
    verify-ndb:
        image: mysql:5.7
        environment:
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=verification
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
        restart: always
# docker-compose -f mysql.yml up -d
# docker-compose -f mysql.yml down