version: '2'

services:
  tarantool1:
    image: tarantool/tarantool:1.6
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2"
    networks:
      - mynet
    ports:
      - "3301:3301"

  tarantool2:
    image: tarantool/tarantool:1.6
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2"
    networks:
      - mynet
    ports:
      - "3302:3301"

networks:
  mynet:
    driver: bridge

# docker-compose -f tarantool.yml up -d
# docker-compose -f tarantool.yml down